screwdriver-cd/buildcluster-queue-worker

- screwdriver.yaml
when doing docker trigger and publish in the same build, it won't be able to get the new tag since the cmd is doing `git tags` from the current repo which doesn't include the new tag that got pushed by semantic-release
> fix: set the correct tag for docker trigger

- config/custom-environment-variables.yaml
- make disk speed label configurable via ENV 
Related to https://github.com/screwdriver-cd/executor-k8s-vm/pull/53
> fix: add disk speed label config [3]

- package.json
pull in latest executor-k8s-vm with preStop hook
https://github.com/screwdriver-cd/executor-k8s-vm/commit/e691cff956993cb12f6be4cc8e0d552a617291c6
https://github.com/screwdriver-cd/screwdriver/issues/1676
> fix: pull in latest executor-k8s-vm

- config/custom-environment-variables.yaml
Make disk space config more generic. 
This PR renames the disk space config from `high` to `space`.
Blocked by https://github.com/screwdriver-cd/executor-k8s-vm/pull/60
> fix: Rename disk space config

- config/custom-environment-variables.yaml
- config/default.yaml
cache strategy and cache path environment variables missing for disk cache strategy
add missing cache strategy and cache path environment variables for disk cache strategy
[1830](https://github.com/screwdriver-cd/screwdriver/issues/1830)
> fix(1830): add cache strategy and cache path environment variables

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
Move cache environment variables under ecosystem and get latest executork8svm
[1830](https://github.com/screwdriver-cd/screwdriver/issues/1830)
> fix(1830): update cache env var path and latest executork8svm

- package.json
Build cache fails with error "permission denied in set cache" when using disk-based strategy, due to permission issue on created folders.
This PR pulls latest executor-k8s-vm which has the fix for cache folder permissions
[1887](https://github.com/screwdriver-cd/screwdriver/issues/1887)
> fix(1887): fix cache folder permissions

- package.json
Enable kata containers to run in privileged mode 
Pull in the latest executor-k8s which has changes related to enabling privileged mode for kata containers.
> feat(818): Enable privileged mode for kata containers

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
By default, k8s pod runs in privileged mode.
Privileged mode is enabled via a flag by admin
> feat(818): Security Context privileged mode configurable via a flag by admin

- config/custom-environment-variables.yaml
- config/default.yaml
make options for service account and automount token as a preferable option for attaching service account instead of overriding token
add config for service account and automount token
https://github.com/screwdriver-cd/screwdriver/issues/1955
https://github.com/screwdriver-cd/executor-k8s/pull/116
> feat: config for serviceAccount and automountServiceAccountToken

- package.json
Top images to be cached in the node are not available as part of the node warm-up.
Pull in latest executor-k8s, which has changes to send image metrics to Prometheus via pushgateway configuration. These metrics will be used to query top n images and cached in node as part of the node warm-up. 
[executor-k8s PR-117](https://github.com/screwdriver-cd/executor-k8s/pull/117)
> feat(818): pull in executor-k8s with metrics push to prometheus

- package.json
missing NODE_ID in metrics
pull in latest executor-k8s - add NODE_ID to metrics
[executor-k8s PR-119](https://github.com/screwdriver-cd/executor-k8s/pull/119)
> feat(818): pull in latest executor-k8s

- package.json
At times the connection to rabbitmq server is lost.
This PR upgrades amqp-connection-manager package version from v2.3.0 [Nov 20, 2018] to v3.2.0 [Jan, 20, 2020].
[screwdriver-cd/screwdriver#2052](https://github.com/screwdriver-cd/screwdriver/issues/2052)
> feat(2052): Upgrade amqp package

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
Add runtime class config to support kata for kubernetes version v1.12.0 or above [kata-containers-as-a-runtimeclass](https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#kata-containers-as-a-runtimeclass).
[executor-k8s PR#121](https://github.com/screwdriver-cd/executor-k8s/pull/121)
> feat(818): add runtimeclass config for kata

- package.json
Pull in latest executor-k8s with metrics push to Prometheus for kata route.
[feat(818): Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[executor-k8s PR#122](https://github.com/screwdriver-cd/executor-k8s/pull/122)
[launcher PR#342](https://github.com/screwdriver-cd/launcher/pull/342)
> feat(818): pull metrics push to prometheus changes

- package.json
executor k8s changes - Suffix buildid-with-prefix to the launcher container name, similar to build container name.
[feat(818): Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[PR#124](https://github.com/screwdriver-cd/executor-k8s/pull/124)
> fix(818): latest executor k8s

- package.json
pipeline-id/job-id/build-id is available in both beta and prod environments, which results in incorrect metrics.
Pull in latest executor k8s, changes related to SD_BUILD_PREFIX env var 
[feat(818): Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[Executor PR-126](https://github.com/screwdriver-cd/executor-k8s/pull/126)
[Launcher PR-352](https://github.com/screwdriver-cd/launcher/pull/352)
> fix(818): add sd build prefix env var changes

- lib/config.js
- test/config.test.js
Fix cacheStrategy and cachePath var declaration
[Cache cleanup is broken when disk-based cache is used](https://github.com/screwdriver-cd/screwdriver/issues/2087)
> fix(2087): cachestrategy and cachepath declaration

- Dockerfile
- index.js
fs-extra module fails with `/usr/src/app/node_modules/fs-extra/lib/mkdirs/make-dir.js:85 } catch { ^ SyntaxError: Unexpected token { ` in node version 8
Upgrade node version to 12
[Cache cleanup is broken when disk based cache is used](https://github.com/screwdriver-cd/screwdriver/issues/2087)
> fix(2087): upgrade node version

- package.json
Revert CPU config to support 0.5
https://github.com/screwdriver-cd/executor-k8s/pull/128
> fix: revert cpu config to support 0.5 values

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
add max memory config to executor-k8s definition
https://github.com/screwdriver-cd/executor-k8s/pull/130
> fix: add memory max configuration to configs

- package.json
Error: tim: 'cache_max_go_threads' not found in {{cache_max_go_threads}}
pull latest executor-k8s-vm with fix
[executor-k8s-vm-PR#76](https://github.com/screwdriver-cd/executor-k8s-vm/pull/76)
[executor-k8s-vm-PR#75](https://github.com/screwdriver-cd/executor-k8s-vm/pull/75)
> fix: typo cache-max_go_threads

- package.json
Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR upgrades hapi and node fixes all schema related changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958
> feat(1959): Publish major version. BREAKING CHANGES: hapi v19 upgrade

- config/custom-environment-variables.yaml
- config/default.yaml
Enable multiple configs of same executor. add k8s-sandbox executor plugin to config. 
Helps to test production build in production cluster. Test builds are routed using nodeSelectors (K8S_SANDBOX_NODE_SELECTORS) annotation.
[buildcluster-queue-worker/pull/76](https://github.com/screwdriver-cd/buildcluster-queue-worker/pull/76)
> add k8s-sandbox executor plugins to configs

- config/custom-environment-variables.yaml
- config/default.yaml
This config will allow cluster admins to set build pod DNS policy.
https://github.com/screwdriver-cd/executor-k8s/pull/133
> fix: add dnsPolicy env variable

- package.json
In Kata setup, build hangs indefinitely in init step for listed container waiting reasons 1. CrashLoopBackOff, 2. CreateContainerConfigError, 3. InvalidImageName, 4. CreateContainerError
Include additional container waiting reasons check 1. CrashLoopBackOff, 2. CreateContainerConfigError, 3. InvalidImageName, 4. CreateContainerError as part of pending retry strategy evaluation.
PR - https://github.com/screwdriver-cd/executor-k8s/pull/138
> fix: upgrade executor-k8s - fix for init container stuck doesn't propagate error

- package.json
In Kata setup, build hangs indefinitely in init step for "StartError" container waiting reason
Include "StartError" container waiting reasons check as part of pending retry strategy evaluation.
PR - https://github.com/screwdriver-cd/executor-k8s/pull/139
> fix: latest executor-k8s

- package.json
When pod is scheduled with invalid image or container without sudo permission it should fail consistently and update build status and message appropriately, but it works intermittently. 
This could be due to delay in k8s updating pod status to failed. Add pod failed status check along-with container state waiting reason check.
https://github.com/screwdriver-cd/executor-k8s/pull/138
https://github.com/screwdriver-cd/executor-k8s/pull/139
https://github.com/screwdriver-cd/executor-k8s/pull/140
> fix: pull in new executor-k8s

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
Add config option to delay pod status pending retry strategy query. 
https://github.com/screwdriver-cd/executor-k8s/pull/138
https://github.com/screwdriver-cd/executor-k8s/pull/139
https://github.com/screwdriver-cd/executor-k8s/pull/140
https://github.com/screwdriver-cd/executor-k8s/pull/141
> fix: add config to delay pod status pending retry strategy query

- config/custom-environment-variables.yaml
- package.json
Currently if a build is aborted the teardown steps don't run and hence generated artifacts are not available in this case, so we need to increase the grace period before pod termination to run the artifact saving steps
This PR adds provision to increase pod timeout by using annotations
https://github.com/screwdriver-cd/screwdriver/issues/1125
> feat: update pkg versions and config

- config/custom-environment-variables.yaml
- config/default.yaml
- test/data/executorConfig.json
- test/data/executorConfigWeightage.json
Cluster admins might want to set custom pod labels.
This PR adds config:
- to allow for custom pod labels
- to set imagePullPolicy
- to configure imagePullSecrets name
Related to https://github.com/screwdriver-cd/screwdriver/issues/2265
> feat(2265): Allow custom podLabels [1]

- package.json
Pull in executor-k8s changes related to Log JSON response, status, and waiting reason when scheduling a build.
https://github.com/screwdriver-cd/executor-k8s/pull/150
> fix: pull in executor-k8s changes related to print build pod response

- config/default.yaml
- lib/config.js
- test/config.test.js
Setting `connectOptions` or `queueOptions` using Kubernetes env was not correctly set. Only strings are allowed in Kubernetes env.
Also, there was a problem in the test code where mock always returned the value defined in `configDef`, so the test always succeeded.
- Fix it so that the values set to `connectOptions` or `queueOptions` are properties of the object.
- Remove `getConfig` mock 
- Compare the value set in `config/default` with the value defined in `confDef`
https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#envvar-v1-core
> fix: rabbitmq config

- config/custom-environment-variables.yaml
- config/default.yaml
- index.js
- lib/config.js
- test/config.test.js
Rabbitmq queue options configuration is defined but not used. 
Remove unused queue options configuration. checkQueue will only validate the queue name and not options. 
https://github.com/screwdriver-cd/screwdriver/issues/2303
> fix (2303): remove unused queueOptions config

- screwdriver.yaml
Functional tests missing for build cluster queue worker
Functional test added after beta deployment to validate that builds can run.
https://github.com/screwdriver-cd/screwdriver/issues/2281
> fix(2281): add functional test

- Dockerfile
I found useless `package-lock.json`
```
root@806c4d313601:/usr/src/app# ls -lh
total 88K
drwxr-xr-x 1 root root 4.0K Jan 22 12:23 node_modules
-rw-r--r-- 1 root root  80K Dec  8 17:25 package-lock.json
```
not to create package-lock.json
- https://docs.npmjs.com/cli/v6/commands/npm-install
> fix: update Dockerfile not to create package-lock.json

- config/custom-environment-variables.yaml
- config/default.yaml
DLC with mounting cache drive is slow with docker builds as it read writes from network drive so we cannot use this approach
This PR removes env vars related to dlc
> feat: revert dlc env vars

- config/custom-environment-variables.yaml
- config/default.yaml
- index.js
- lib/server.js
- package.json
- test/server.test.js
In buildcluster-queue-worker, there was no endpoint that could be monitored using liveness.
Add liveness(`/health`) endpoint.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2343
> fix(2343): Add liveness endpoint

- receiver.js
onRetryMessage fn was reading the incorrect config
This PR fixes reading config in onRetrymessage fn
> feat: fix retry msg config

- package.json
- receiver.js
Add log messages, start condition for retry
This PR adds log messages and condition `jobType === 'start'` for retrying messages
> feat: Add log messages, start condition for retry

- receiver.js
Worker should requeue verify jobs on nack instead of dead lettering them as we want to check the status for all retry builds and either mark them FAILURE or acknowledge
This PR re-queues verify jobs instead of dead lettering on a negative acknowledgment
> feat: requeue verify jobs instead of deadlettering

- receiver.js
We want to control the delivery time of messages before checking for status again
This PR reverts the re-queuing logic of messages and instead relies on dead lettering for timely delivery of messages
> fix: revert re-queue of messages and push to dead letter

- receiver.js
Worker spawns a thread for each message which need to be cleaned else will clog the memory
This PR adds the missing `thread.kill` to clean up any process that was completed.
> fix: add missing thread kill which backs up memory

- config/default.yaml
- lib/config.js
- receiver.js
- test/config.test.js
- test/receiver.test.js
The value of RABBITMQ_RETRYQUEUE_ENABLED is not read as boolean, so it is enabled even if false is set.
Even if the Retry Queue feature is disabled, it will try to connect to the default retryQueue (sdRetryQueue), so it will output an error log many times.
This PR adds check for retry enabled flag and does not connect to retry queue by default
https://github.com/screwdriver-cd/screwdriver/issues/2491#issuecomment-938378922
> feat: fix default for retry queue

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
Habitat installation needs to be optional for the launcher
This PR adds the flag `SD_HAB_ENABLED` to the executor's configuration
https://github.com/screwdriver-cd/launcher/pull/429
https://github.com/screwdriver-cd/executor-k8s/pull/178
> feat(#1658): Add flag for hab install

- Dockerfile
[The previous PR](https://github.com/screwdriver-cd/buildcluster-queue-worker/pull/98) disabled package-lock.json, but package-lock.json is useful for clarifying the package version in the image, so re-enable it. 
package-lock.json is placed in the image.
> fix: create package-lock

- index.js
When connecting to RabbitMQ, the following error message displayed. 
```
Debug: internal, implementation, error 
TypeError: amqpConnection.isConnected is not a function
at handler (/usr/src/app/node_modules/screwdriver-buildcluster-queue-worker/lib/server.js:30:40)
```
The reason for this is simple: you have not await the [promise](https://github.com/screwdriver-cd/buildcluster-queue-worker/blob/7c410ba66da15bd2868f9743ca7197938d95c08b/receiver.js#L218).
Correct use of `async/await`.
https://github.com/screwdriver-cd/screwdriver/issues/2491#issuecomment-940697541
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
> fix(2491): health check processing error

- receiver.js
When `executor.start` returns 403/404 error, then buildcluster-queue-worker requeue the job, but the executor will return 403/404 error again when retry the job.
Thus it will requeue up to the `messageReprocessLimit`, and the queue will be jammed.
Make the job is not requeued when executor returns 403/404 error.
> fix: do not requeue when executor returns 403 or 404 error

- receiver.js
We have found that the buildcluster-queue-worker is occasionally killed due to OOM when the number of parallel builds is high. 
Since the current log information does not allow us to determine whether the failure was due to OOM, we will add an exit code to the log so that the cause of failure can be identified from the log.
The exit code will be null if an OOM occurs, and 143(SIGTERM) if not.
- add exit code to log
> add: exit code to info log

- package.json
make release of buildcluster-queue-worker
pull in latest dependency on executors
> fix: pull in latest executors

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- test/data/executorConfig.json
- test/data/executorConfigWeightage.json
- test/jobs.test.js
Reverts screwdriver-cd/buildcluster-queue-worker#160
We are still seeing some use cases of `k8s-vm` so we cannot really remove this dependency right now.
> Revert "fix(3055): remove k8s-vm dependence"
