screwdriver-cd/buildcluster-queue-worker

README.md, index.js
update pipelineid and remove k8s reference
=> feat(1319): build cluster queue worker / consumer

config/default.yaml
fix for type error and commit msg format
=> fix: type error and commit msg format

config/default.yaml
fix: SD Failed to publish release notes error
=> fix: SD Failed to publish release notes error

screwdriver.yaml
add k8s deployment for bf1 worker
=> fix: add deployment for bf1 worker

config/custom-environment-variables.yaml, config/default.yaml, package.json
pull in new executor-k8s-vm with custom cpu and ram: new executor-k8s-vm with custom cpu and ram
=> fix: pull in new executor-k8s-vm with custom cpu and ram

config/custom-environment-variables.yaml, config/default.yaml
Same fixes with https://github.com/screwdriver-cd/queue-worker/pull/129
https://github.com/screwdriver-cd/screwdriver/issues/1678
=> fix(1678): [1] add requestretry options

index.js, lib/jobs.js, package.json
Use screwdriver-logger
https://github.com/screwdriver-cd/logger
=> fix: use screwdriver-logger

config/custom-environment-variables.yaml, config/default.yaml, package.json
Move cache strategy config under ecosystem and up executor-k8s-vm version
[1830]
=> fix(1830): update env var and up k8s-vm version

package.json
Kata containers flow will be via executor-k8s; need to pull in the latest executor-k8s.
Pull in executor-k8s with Disk-based cache strategy implementation.
[Build cache - disk storage strategy](https://github.com/screwdriver-cd/screwdriver/issues/1830)
=> feat(818): Evaluate Kata Containers over HyperD

config/custom-environment-variables.yaml
add container lifecycle hooks from env
add container lifecycle hooks from env
https://github.com/screwdriver-cd/executor-k8s/pull/125
=> feat: add container lifecycle hooks

config/custom-environment-variables.yaml, config/default.yaml, package.json
Fetch latest executor-router
This PR updates the router version.
=> feat(2083): update executor-router package version

package.json
update package version 
update package version 
=> fix: update package version

package.json
Update latest executor-k8s version - changes related to cpu config and runtime env variable
https://github.com/screwdriver-cd/executor-k8s/pull/127
=> fix: upd executor-k8s version

config/custom-environment-variables.yaml, config/default.yaml
add max cpu config to executor-k8s
=> fix: add max cpu config to executor-k8s

config/custom-environment-variables.yaml, config/default.yaml, package.json
add cache max go threads config
https://github.com/screwdriver-cd/store-cli/pull/61
=> fix: add cache max go threads config

config/default.yaml, lib/jobs.js
Enable multiple configs of same executor
=> fix: enable setting name

config/custom-environment-variables.yaml, config/default.yaml, package.json
Add config support to mount host devices
https://github.com/screwdriver-cd/executor-k8s/pull/134 
=> fix: config to suport host devices

package.json
add volume mount type
https://github.com/screwdriver-cd/executor-k8s/pull/135
=> fix: add volume Mount type

screwdriver.yaml
Fix functional test job name
https://github.com/screwdriver-cd/screwdriver/issues/2281
https://github.com/screwdriver-cd/buildcluster-queue-worker/pull/96
=> fix(2281): fix functional test job name

config/custom-environment-variables.yaml, config/default.yaml
Support docker layer caching in SD
This PR adds env variables for dlc flag and path
=> feat: add env var for dlc

screwdriver.yaml
update k8s host
update k8s host
=> fix: update  k8s host [skip ci]

package.json
Deploy a new version of worker with updated executor-k8s
This PR updates executor-k8s version
=> feat: deploy new version

receiver.js
Release new version
Release new version
=> fix: release new version

receiver.js
Fix a bug with job type
Fix a bug with jobtype
=> fix: job type error

package.json, receiver.js
Pull latest package versions for dependencies
Pull latest package versions for dependencies
=> feat: pull latest pkg versions for dependencies

receiver.js
Error handling was not added to build status update and caused an unhandled error
This PR adds error handling to build status update failure.
=> fix: handle build status update error

lib/cache.js, lib/config.js, lib/helper.js, lib/jobs.js, lib/retry-queue.js, lib/server.js, package.json, receiver.js, test/cache.test.js, test/config.test.js, test/helper.test.js, test/jobs.test.js, test/receiver.test.js, test/server.test.js
This PR updates eslint-config-screwdriver package to v5.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2492
=> feat(2492): Update to eslint-config-screwdriver v5

config/custom-environment-variables.yaml, config/default.yaml
adding sshca secret
adding sshca secret
=> adding sshca config

screwdriver.yaml
https://github.com/screwdriver-cd/screwdriver/issues/2514
=> fix: use dind to build image

lib/helper.js, package.json, receiver.js, test/helper.test.js
It would be nice to replace deprecated request package with a different one.
This PR attempts to replace [request package](https://www.npmjs.com/package/request) with [got package](https://github.com/sindresorhus/got).
Related to https://github.com/screwdriver-cd/screwdriver/issues/1961
=> feat(1961): Use screwdriver-request package

package.json
=> fix: trigger release

config/custom-environment-variables.yaml, config/default.yaml
current way of serving ssh key as env variable is not ideal
serve ssh key as file instead
https://github.com/screwdriver-cd/screwdriver/issues/2531
=> fix(2531): add secret file

package.json
Deploy worker with latest executor-k8s pkg
This PR deploys a new version
=> feat: pull latest executor-k8s

package.json, screwdriver.yaml, test/cache.test.js, test/jobs.test.js
https://github.com/screwdriver-cd/screwdriver/issues/2683
=> feat(2683): nodejs upgrade

screwdriver.yaml
=> fix: change node image to 18

package.json
Pull in latest update in executor-k8s.
https://github.com/screwdriver-cd/executor-k8s/pull/186
Update package.json
https://github.com/screwdriver-cd/screwdriver/issues/2882
=> fix(2882): pull in latest executor-k8s

package.json
pull in latest so as to bump version
=> fix: pull in latest executor-k8s

receiver.js
thread will leak if there is a cache strategy error which doesn't kill the thread
=> fix: thread leak in receiver

Dockerfile, package.json, screwdriver.yaml
BREAKING CHANGE: Node22
Update Node.js and dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/3282
=> feat(3282): upgrade Node.js v22 and dependencies. BREAKING CHANGE: Node22
